# Generated by Django 5.1.15 on 2026-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenanceresult',
            name='source_type',
            field=models.CharField(choices=[('phash_match', 'pHash Match'), ('clip_neighbour', 'CLIP Semantic Neighbour'), ('tineye', 'TinEye'), ('google_vision', 'Google Vision'), ('c2pa', 'C2PA')], db_index=True, max_length=30),
        ),
    ]
