# Generated by Django 5.1.15 on 2026-04-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dhash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='phash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
