# Generated by Django 5.1.15 on 2026-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_submission_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='approved_for_training',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='verified_label',
            field=models.CharField(blank=True, choices=[('real', 'Real'), ('fake', 'Fake')], max_length=10),
        ),
    ]
