# Generated by Django 5.1.15 on 2026-05-18 11:37

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_pgvector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knownfakehash',
            name='dhash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='knownfakehash',
            name='pdq_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='knownfakehash',
            name='phash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='clip_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='pdq_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='pdq_quality',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['clip_embedding'], m=16, name='submissions_clip_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
