# Generated by Django 5.1.15 on 2026-06-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_submission_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'anonymous_quota',
                'unique_together': {('ip_hash', 'date')},
            },
        ),
    ]
