# Generated by Django 5.1.15 on 2026-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_anonymousquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
