# Generated by Django 5.1.15 on 2026-04-17 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('authentic', 'Authentic'), ('suspicious', 'Suspicious'), ('fake', 'Fake'), ('inconclusive', 'Inconclusive'), ('error', 'Error')], max_length=20)),
                ('evidence', models.JSONField(default=dict)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyzerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('analyzer_class', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('queue', models.CharField(default='default', max_length=50)),
                ('timeout', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyzer_configs',
            },
        ),
    ]
