# Generated by Django 5.1.15 on 2026-04-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzers', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='content.submission'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analyzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='analyzers.analyzerconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('submission', 'analyzer')},
        ),
    ]
