# Generated by Django 5.1.15 on 2026-05-31 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrainRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(default='image', max_length=20)),
                ('samples_used', models.PositiveIntegerField(default=0)),
                ('epochs', models.PositiveIntegerField(default=3)),
                ('hf_revision', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='started', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retrain_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
