import base64
import io
import json
import logging
import re

import requests as http_requests
from PIL import Image
from django.conf import settings

from analyzers.base import AnalysisOutput, BaseAnalyzer

MAX_VISION_DIM = 672
VISION_JPEG_QUALITY = 82

logger = logging.getLogger(__name__)


def _encode_image_for_vision(file_path: str) -> str:
    img = Image.open(file_path)
    img = img.convert("RGB")
    if max(img.size) > MAX_VISION_DIM:
        img.thumbnail((MAX_VISION_DIM, MAX_VISION_DIM), Image.Resampling.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=VISION_JPEG_QUALITY)
    return base64.b64encode(buf.getvalue()).decode("utf-8")


VERDICT_CONFIDENCE = {
    "ai_generated": 0.6,
    "human_photo": 0.6,
    "uncertain": 0.5,
}

WEAK_REASONING_CONFIDENCE = 0.35
WEAK_REASONING_FALLBACK = "Model returned a verdict without detailed reasoning. Downgraded to uncertain pending corroboration from other analyzers."

MIN_REASONING_LEN = 20


def _parse_vision_response(raw: str) -> tuple[str, float, str]:
    raw = (raw or "").strip()
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        try:
            data = json.loads(match.group(0))
            verdict = str(data.get("verdict", "uncertain")).lower()
            reasoning = str(data.get("reasoning", "")).strip()
            if verdict in VERDICT_CONFIDENCE:
                if len(reasoning) >= MIN_REASONING_LEN:
                    return verdict, VERDICT_CONFIDENCE[verdict], reasoning
                return "uncertain", WEAK_REASONING_CONFIDENCE, WEAK_REASONING_FALLBACK
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

    text = raw.lower()

    ai_signals = ("ai-generated", "ai generated", "synthetic image", "artificially generated", "generated by ai", "deepfake", "this is fake", "looks fake", "computer-generated")
    human_signals = ("real photo", "authentic photo", "genuine photo", "human photo", "not ai-generated", "natural photograph", "real photograph", "looks authentic", "looks real")

    has_ai = any(s in text for s in ai_signals)
    has_human = any(s in text for s in human_signals)

    if has_ai and not has_human and len(text) >= MIN_REASONING_LEN:
        return "ai_generated", 0.55, raw[:500]
    if has_human and not has_ai and len(text) >= MIN_REASONING_LEN:
        return "human_photo", 0.55, raw[:500]
    return "model_failure", 0.0, raw[:500]

LLM_IMAGE_PROMPT = """You are a cautious forensic image analyst. Your default assumption is that the image is a real photograph. You will ONLY mark it as AI-generated if you can point to concrete, specific visual defects that are CLEARLY visible in this exact image. Generic descriptions of what AI images "usually" look like are NOT acceptable evidence.

Rules:
- If you cannot describe a SPECIFIC pixel-level defect you actually see (e.g. "the left hand has six fingers", "the text on the sign reads 'AURESTHURT' which is not a word", "the left earring is a sphere while the right is a cube"), the verdict MUST be human_photo or uncertain.
- Famous people, professional studio lighting, smooth skin from makeup, blurry backgrounds from shallow depth of field, and perfect composition are NORMAL in real photography. None of these alone are evidence of AI.
- If the image is low-resolution, compressed, or has heavy JPEG artifacts, that is NOT evidence of AI - it is just bad compression. Verdict should be uncertain.
- Stylised photography (fashion, portrait, advertising) is NOT AI by default.
- The word "uncanny" is NOT evidence. The word "too perfect" is NOT evidence. The word "overly smooth" is NOT evidence unless you specify which region and what the specific defect is.

Respond ONLY with JSON in this exact shape:
{"verdict": "ai_generated|human_photo|uncertain", "confidence": 0.0-1.0, "reasoning": "Either describe SPECIFIC visible defects with their location in the frame, or state that no concrete defects are visible and the image looks like a normal photograph."}

If unsure, choose uncertain. Being wrong on a real photo is worse than being wrong on an AI image."""


class LLMImageAnalyzer(BaseAnalyzer):
    name = "llm_vision"
    version = "1.0.0"

    def supported_mime_types(self) -> list[str]:
        return ["image/jpeg", "image/png", "image/webp"]

    def analyze(self, file_path: str, metadata: dict) -> AnalysisOutput:
        ollama_url = getattr(settings, "OLLAMA_URL", "http://ollama:11434")
        vision_model = getattr(settings, "OLLAMA_VISION_MODEL", "llava:7b")

        try:
            image_b64 = _encode_image_for_vision(file_path)
        except Exception as exc:
            return AnalysisOutput(confidence=0.0, verdict="error", evidence={"error": str(exc)})

        try:
            response = http_requests.post(
                f"{ollama_url}/api/generate",
                json={
                    "model": vision_model,
                    "prompt": LLM_IMAGE_PROMPT,
                    "images": [image_b64],
                    "stream": False,
                    "format": "json",
                },
                timeout=300,
            )
            response.raise_for_status()
            raw = response.json().get("response", "")
            llm_verdict, llm_confidence, reasoning = _parse_vision_response(raw)

            if llm_verdict == "ai_generated":
                verdict = "fake"
            elif llm_verdict == "human_photo":
                verdict = "authentic"
            elif llm_verdict == "model_failure":
                verdict = "error"
            else:
                verdict = "inconclusive"

            return AnalysisOutput(
                confidence=llm_confidence,
                verdict=verdict,
                evidence={"llm_verdict": llm_verdict, "reasoning": reasoning},
            )
        except Exception as exc:
            logger.warning("LLM vision analysis failed: %s", exc)
            return AnalysisOutput(confidence=0.5, verdict="inconclusive", evidence={"error": str(exc)})
